# Generated by Django 6.0.2 on 2026-02-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source_url', models.URLField()),
                ('published_date', models.DateField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='tools.tool')),
            ],
        ),
    ]
